# Generated by Django 3.0.5 on 2021-10-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caesarapp', '0003_auto_20160331_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinput',
            name='hill_key',
            field=models.CharField(default='abvs', max_length=140),
        ),
    ]
